name: SpawnerFF
version: '1.0'
main: com.farmforge.spawners.plugin.SpawnersFF
api-version: '1.21'
authors: [ adeseyn ]
description: Plugin for spawners in Minecraft.

commands:
  givespawner:
    description: Gives a spawner
    usage: /givespawner [type] [tier]
  spawnerupgrade:
    description: Upgrades a spawner stat
    usage: /spawnerupgrade <spawnerId> <speed|capacity|drop>